version: '3.2'

services:
  eurekasrv:
    image:   spring-cloud/eurekasrv:version1
    ports:
    - "8761:8761"

  zuulsrv:
    image: spring-cloud/zuulsrv:version1
    ports:
    - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configsrv:8888"
      EUREKASERVER_URI: "http://eurekasrv:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"


  configsrv:
    image: spring-cloud/confsrv:version1
    ports:
    - "8888:8888"
    environment:
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_URI: "http://eurekasrv:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "SIMPLEKEY"
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}"
    extra_hosts:
    - "database:${DOCKER_HOST_IP}"

  userservice:
    image: spring-cloud/userservice:version1
    ports:
    - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configsrv:8888"
      EUREKASERVER_URI: "http://eurekasrv:8761/eureka/"
      AUTHSERVER_URI:   "http://authsrv:8901/auth/user"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "SIMPLEKEY"
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}"
    extra_hosts:
    - "database:${DOCKER_HOST_IP}"

  orderservice:
    image: spring-cloud/orderservice:version1
    ports:
    - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configsrv:8888"
      EUREKASERVER_URI: "http://eurekasrv:8761/eureka/"
      AUTHSERVER_URI:   "http://authsrv:8901/auth/user"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "SIMPLEKEY"
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}"
    extra_hosts:
    - "database:${DOCKER_HOST_IP}"

  authsrv:
    image: spring-cloud/authsrv:version1
    ports:
    - "8901:8901"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8901"
      DATABASE_PORT: "5432"
      CONFIGSERVER_PORT: "8888"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://configsrv:8888"
      EUREKASERVER_URI: "http://eurekasrv:8761/eureka/"
      ENCRYPT_KEY:       "SIMPLEKEY"
      DOCKER_HOST_IP: ${DOCKER_HOST_IP}"
    extra_hosts:
    - "database:${DOCKER_HOST_IP}"



