version: '3'

services:
  eurekasrv:
    image:   spring-cloud/eurekasrv:version1
    ports:
    - "8761:8761"

  zuulsrv:
    image: spring-cloud/zuulsrv:version1
    ports:
    - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configsrv:8888"
      EUREKASERVER_URI: "http://eurekasrv:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "5432"
      CONFIGSERVER_PORT:        "8888"


  configsrv:
    image: spring-cloud/confsrv:version1
    ports:
    - "8888:8888"
    environment:
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_URI: "http://eurekasrv:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "SIMPLEKEY"
    extra_hosts:
    - "database:192.168.0.100"

  userservice:
    image: spring-cloud/userservice:version1
    ports:
    - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configsrv:8888"
      EUREKASERVER_URI: "http://eurekasrv:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "SIMPLEKEY"
    extra_hosts:
    - "database:192.168.0.100"

  orderservice:
    image: spring-cloud/orderservice:version1
    ports:
    - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configsrv:8888"
      EUREKASERVER_URI: "http://eurekasrv:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY:       "SIMPLEKEY"
    extra_hosts:
    - "database:192.168.0.100"


