version:  '2'
services:
  configsrv:
    extends:
      file: ../common/docker-compose.yml
      service: configsrv
  userservice:
      image: spring-cloud/userservice:version1
      ports:
        - "8080:8080"
      environment:
        PROFILE: "prod"
        CONFIGSERVER_URI: "http://configsrv:8888"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "5432"
